sudo: required
services:
    - docker

before_install:
  - docker build -t raghunandanamr/docker-react -f Dockerfile.dev .

script:
  - docker run raghunandanamr/docker-react npm run test -- --coverage